// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake
{
    public static class GetPagespeedMonitoringLocations
    {
        public static Task<GetPagespeedMonitoringLocationsResult> InvokeAsync(GetPagespeedMonitoringLocationsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPagespeedMonitoringLocationsResult>("statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations", args ?? new GetPagespeedMonitoringLocationsArgs(), options.WithDefaults());

        public static Output<GetPagespeedMonitoringLocationsResult> Invoke(GetPagespeedMonitoringLocationsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPagespeedMonitoringLocationsResult>("statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations", args ?? new GetPagespeedMonitoringLocationsInvokeArgs(), options.WithDefaults());

        public static Output<GetPagespeedMonitoringLocationsResult> Invoke(GetPagespeedMonitoringLocationsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPagespeedMonitoringLocationsResult>("statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations", args ?? new GetPagespeedMonitoringLocationsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPagespeedMonitoringLocationsArgs : global::Pulumi.InvokeArgs
    {
        [Input("regionCode")]
        public string? RegionCode { get; set; }

        public GetPagespeedMonitoringLocationsArgs()
        {
        }
        public static new GetPagespeedMonitoringLocationsArgs Empty => new GetPagespeedMonitoringLocationsArgs();
    }

    public sealed class GetPagespeedMonitoringLocationsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("regionCode")]
        public Input<string>? RegionCode { get; set; }

        public GetPagespeedMonitoringLocationsInvokeArgs()
        {
        }
        public static new GetPagespeedMonitoringLocationsInvokeArgs Empty => new GetPagespeedMonitoringLocationsInvokeArgs();
    }


    [OutputType]
    public sealed class GetPagespeedMonitoringLocationsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetPagespeedMonitoringLocationsLocationResult> Locations;
        public readonly string? RegionCode;

        [OutputConstructor]
        private GetPagespeedMonitoringLocationsResult(
            string id,

            ImmutableArray<Outputs.GetPagespeedMonitoringLocationsLocationResult> locations,

            string? regionCode)
        {
            Id = id;
            Locations = locations;
            RegionCode = regionCode;
        }
    }
}
