// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake
{
    [StatuscakeResourceType("statuscake:index/heartbeatCheck:HeartbeatCheck")]
    public partial class HeartbeatCheck : global::Pulumi.CustomResource
    {
        /// <summary>
        /// URL of the heartbeat check
        /// </summary>
        [Output("checkUrl")]
        public Output<string> CheckUrl { get; private set; } = null!;

        /// <summary>
        /// List of contact group IDs
        /// </summary>
        [Output("contactGroups")]
        public Output<ImmutableArray<string>> ContactGroups { get; private set; } = null!;

        /// <summary>
        /// Monitored resource configuration block. This describes the server under test
        /// </summary>
        [Output("monitoredResource")]
        public Output<Outputs.HeartbeatCheckMonitoredResource?> MonitoredResource { get; private set; } = null!;

        /// <summary>
        /// Name of the check
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Whether the check should be run
        /// </summary>
        [Output("paused")]
        public Output<bool?> Paused { get; private set; } = null!;

        /// <summary>
        /// Number of seconds since the last ping before the check is considered down.
        /// </summary>
        [Output("period")]
        public Output<int> Period { get; private set; } = null!;

        /// <summary>
        /// List of tags
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a HeartbeatCheck resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public HeartbeatCheck(string name, HeartbeatCheckArgs args, CustomResourceOptions? options = null)
            : base("statuscake:index/heartbeatCheck:HeartbeatCheck", name, args ?? new HeartbeatCheckArgs(), MakeResourceOptions(options, ""))
        {
        }

        private HeartbeatCheck(string name, Input<string> id, HeartbeatCheckState? state = null, CustomResourceOptions? options = null)
            : base("statuscake:index/heartbeatCheck:HeartbeatCheck", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing HeartbeatCheck resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static HeartbeatCheck Get(string name, Input<string> id, HeartbeatCheckState? state = null, CustomResourceOptions? options = null)
        {
            return new HeartbeatCheck(name, id, state, options);
        }
    }

    public sealed class HeartbeatCheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("contactGroups")]
        private InputList<string>? _contactGroups;

        /// <summary>
        /// List of contact group IDs
        /// </summary>
        public InputList<string> ContactGroups
        {
            get => _contactGroups ?? (_contactGroups = new InputList<string>());
            set => _contactGroups = value;
        }

        /// <summary>
        /// Monitored resource configuration block. This describes the server under test
        /// </summary>
        [Input("monitoredResource")]
        public Input<Inputs.HeartbeatCheckMonitoredResourceArgs>? MonitoredResource { get; set; }

        /// <summary>
        /// Name of the check
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether the check should be run
        /// </summary>
        [Input("paused")]
        public Input<bool>? Paused { get; set; }

        /// <summary>
        /// Number of seconds since the last ping before the check is considered down.
        /// </summary>
        [Input("period", required: true)]
        public Input<int> Period { get; set; } = null!;

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of tags
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public HeartbeatCheckArgs()
        {
        }
        public static new HeartbeatCheckArgs Empty => new HeartbeatCheckArgs();
    }

    public sealed class HeartbeatCheckState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL of the heartbeat check
        /// </summary>
        [Input("checkUrl")]
        public Input<string>? CheckUrl { get; set; }

        [Input("contactGroups")]
        private InputList<string>? _contactGroups;

        /// <summary>
        /// List of contact group IDs
        /// </summary>
        public InputList<string> ContactGroups
        {
            get => _contactGroups ?? (_contactGroups = new InputList<string>());
            set => _contactGroups = value;
        }

        /// <summary>
        /// Monitored resource configuration block. This describes the server under test
        /// </summary>
        [Input("monitoredResource")]
        public Input<Inputs.HeartbeatCheckMonitoredResourceGetArgs>? MonitoredResource { get; set; }

        /// <summary>
        /// Name of the check
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether the check should be run
        /// </summary>
        [Input("paused")]
        public Input<bool>? Paused { get; set; }

        /// <summary>
        /// Number of seconds since the last ping before the check is considered down.
        /// </summary>
        [Input("period")]
        public Input<int>? Period { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of tags
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public HeartbeatCheckState()
        {
        }
        public static new HeartbeatCheckState Empty => new HeartbeatCheckState();
    }
}
