// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package statuscake

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-statuscake/sdk/go/statuscake/internal"
)

type HeartbeatCheck struct {
	pulumi.CustomResourceState

	// URL of the heartbeat check
	CheckUrl pulumi.StringOutput `pulumi:"checkUrl"`
	// List of contact group IDs
	ContactGroups pulumi.StringArrayOutput `pulumi:"contactGroups"`
	// Monitored resource configuration block. This describes the server under test
	MonitoredResource HeartbeatCheckMonitoredResourcePtrOutput `pulumi:"monitoredResource"`
	// Name of the check
	Name pulumi.StringOutput `pulumi:"name"`
	// Whether the check should be run
	Paused pulumi.BoolPtrOutput `pulumi:"paused"`
	// Number of seconds since the last ping before the check is considered down.
	Period pulumi.IntOutput `pulumi:"period"`
	// List of tags
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
}

// NewHeartbeatCheck registers a new resource with the given unique name, arguments, and options.
func NewHeartbeatCheck(ctx *pulumi.Context,
	name string, args *HeartbeatCheckArgs, opts ...pulumi.ResourceOption) (*HeartbeatCheck, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Period == nil {
		return nil, errors.New("invalid value for required argument 'Period'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource HeartbeatCheck
	err := ctx.RegisterResource("statuscake:index/heartbeatCheck:HeartbeatCheck", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHeartbeatCheck gets an existing HeartbeatCheck resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHeartbeatCheck(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HeartbeatCheckState, opts ...pulumi.ResourceOption) (*HeartbeatCheck, error) {
	var resource HeartbeatCheck
	err := ctx.ReadResource("statuscake:index/heartbeatCheck:HeartbeatCheck", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HeartbeatCheck resources.
type heartbeatCheckState struct {
	// URL of the heartbeat check
	CheckUrl *string `pulumi:"checkUrl"`
	// List of contact group IDs
	ContactGroups []string `pulumi:"contactGroups"`
	// Monitored resource configuration block. This describes the server under test
	MonitoredResource *HeartbeatCheckMonitoredResource `pulumi:"monitoredResource"`
	// Name of the check
	Name *string `pulumi:"name"`
	// Whether the check should be run
	Paused *bool `pulumi:"paused"`
	// Number of seconds since the last ping before the check is considered down.
	Period *int `pulumi:"period"`
	// List of tags
	Tags []string `pulumi:"tags"`
}

type HeartbeatCheckState struct {
	// URL of the heartbeat check
	CheckUrl pulumi.StringPtrInput
	// List of contact group IDs
	ContactGroups pulumi.StringArrayInput
	// Monitored resource configuration block. This describes the server under test
	MonitoredResource HeartbeatCheckMonitoredResourcePtrInput
	// Name of the check
	Name pulumi.StringPtrInput
	// Whether the check should be run
	Paused pulumi.BoolPtrInput
	// Number of seconds since the last ping before the check is considered down.
	Period pulumi.IntPtrInput
	// List of tags
	Tags pulumi.StringArrayInput
}

func (HeartbeatCheckState) ElementType() reflect.Type {
	return reflect.TypeOf((*heartbeatCheckState)(nil)).Elem()
}

type heartbeatCheckArgs struct {
	// List of contact group IDs
	ContactGroups []string `pulumi:"contactGroups"`
	// Monitored resource configuration block. This describes the server under test
	MonitoredResource *HeartbeatCheckMonitoredResource `pulumi:"monitoredResource"`
	// Name of the check
	Name *string `pulumi:"name"`
	// Whether the check should be run
	Paused *bool `pulumi:"paused"`
	// Number of seconds since the last ping before the check is considered down.
	Period int `pulumi:"period"`
	// List of tags
	Tags []string `pulumi:"tags"`
}

// The set of arguments for constructing a HeartbeatCheck resource.
type HeartbeatCheckArgs struct {
	// List of contact group IDs
	ContactGroups pulumi.StringArrayInput
	// Monitored resource configuration block. This describes the server under test
	MonitoredResource HeartbeatCheckMonitoredResourcePtrInput
	// Name of the check
	Name pulumi.StringPtrInput
	// Whether the check should be run
	Paused pulumi.BoolPtrInput
	// Number of seconds since the last ping before the check is considered down.
	Period pulumi.IntInput
	// List of tags
	Tags pulumi.StringArrayInput
}

func (HeartbeatCheckArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*heartbeatCheckArgs)(nil)).Elem()
}

type HeartbeatCheckInput interface {
	pulumi.Input

	ToHeartbeatCheckOutput() HeartbeatCheckOutput
	ToHeartbeatCheckOutputWithContext(ctx context.Context) HeartbeatCheckOutput
}

func (*HeartbeatCheck) ElementType() reflect.Type {
	return reflect.TypeOf((**HeartbeatCheck)(nil)).Elem()
}

func (i *HeartbeatCheck) ToHeartbeatCheckOutput() HeartbeatCheckOutput {
	return i.ToHeartbeatCheckOutputWithContext(context.Background())
}

func (i *HeartbeatCheck) ToHeartbeatCheckOutputWithContext(ctx context.Context) HeartbeatCheckOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HeartbeatCheckOutput)
}

// HeartbeatCheckArrayInput is an input type that accepts HeartbeatCheckArray and HeartbeatCheckArrayOutput values.
// You can construct a concrete instance of `HeartbeatCheckArrayInput` via:
//
//	HeartbeatCheckArray{ HeartbeatCheckArgs{...} }
type HeartbeatCheckArrayInput interface {
	pulumi.Input

	ToHeartbeatCheckArrayOutput() HeartbeatCheckArrayOutput
	ToHeartbeatCheckArrayOutputWithContext(context.Context) HeartbeatCheckArrayOutput
}

type HeartbeatCheckArray []HeartbeatCheckInput

func (HeartbeatCheckArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HeartbeatCheck)(nil)).Elem()
}

func (i HeartbeatCheckArray) ToHeartbeatCheckArrayOutput() HeartbeatCheckArrayOutput {
	return i.ToHeartbeatCheckArrayOutputWithContext(context.Background())
}

func (i HeartbeatCheckArray) ToHeartbeatCheckArrayOutputWithContext(ctx context.Context) HeartbeatCheckArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HeartbeatCheckArrayOutput)
}

// HeartbeatCheckMapInput is an input type that accepts HeartbeatCheckMap and HeartbeatCheckMapOutput values.
// You can construct a concrete instance of `HeartbeatCheckMapInput` via:
//
//	HeartbeatCheckMap{ "key": HeartbeatCheckArgs{...} }
type HeartbeatCheckMapInput interface {
	pulumi.Input

	ToHeartbeatCheckMapOutput() HeartbeatCheckMapOutput
	ToHeartbeatCheckMapOutputWithContext(context.Context) HeartbeatCheckMapOutput
}

type HeartbeatCheckMap map[string]HeartbeatCheckInput

func (HeartbeatCheckMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HeartbeatCheck)(nil)).Elem()
}

func (i HeartbeatCheckMap) ToHeartbeatCheckMapOutput() HeartbeatCheckMapOutput {
	return i.ToHeartbeatCheckMapOutputWithContext(context.Background())
}

func (i HeartbeatCheckMap) ToHeartbeatCheckMapOutputWithContext(ctx context.Context) HeartbeatCheckMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HeartbeatCheckMapOutput)
}

type HeartbeatCheckOutput struct{ *pulumi.OutputState }

func (HeartbeatCheckOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HeartbeatCheck)(nil)).Elem()
}

func (o HeartbeatCheckOutput) ToHeartbeatCheckOutput() HeartbeatCheckOutput {
	return o
}

func (o HeartbeatCheckOutput) ToHeartbeatCheckOutputWithContext(ctx context.Context) HeartbeatCheckOutput {
	return o
}

// URL of the heartbeat check
func (o HeartbeatCheckOutput) CheckUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *HeartbeatCheck) pulumi.StringOutput { return v.CheckUrl }).(pulumi.StringOutput)
}

// List of contact group IDs
func (o HeartbeatCheckOutput) ContactGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HeartbeatCheck) pulumi.StringArrayOutput { return v.ContactGroups }).(pulumi.StringArrayOutput)
}

// Monitored resource configuration block. This describes the server under test
func (o HeartbeatCheckOutput) MonitoredResource() HeartbeatCheckMonitoredResourcePtrOutput {
	return o.ApplyT(func(v *HeartbeatCheck) HeartbeatCheckMonitoredResourcePtrOutput { return v.MonitoredResource }).(HeartbeatCheckMonitoredResourcePtrOutput)
}

// Name of the check
func (o HeartbeatCheckOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *HeartbeatCheck) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Whether the check should be run
func (o HeartbeatCheckOutput) Paused() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *HeartbeatCheck) pulumi.BoolPtrOutput { return v.Paused }).(pulumi.BoolPtrOutput)
}

// Number of seconds since the last ping before the check is considered down.
func (o HeartbeatCheckOutput) Period() pulumi.IntOutput {
	return o.ApplyT(func(v *HeartbeatCheck) pulumi.IntOutput { return v.Period }).(pulumi.IntOutput)
}

// List of tags
func (o HeartbeatCheckOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HeartbeatCheck) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

type HeartbeatCheckArrayOutput struct{ *pulumi.OutputState }

func (HeartbeatCheckArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HeartbeatCheck)(nil)).Elem()
}

func (o HeartbeatCheckArrayOutput) ToHeartbeatCheckArrayOutput() HeartbeatCheckArrayOutput {
	return o
}

func (o HeartbeatCheckArrayOutput) ToHeartbeatCheckArrayOutputWithContext(ctx context.Context) HeartbeatCheckArrayOutput {
	return o
}

func (o HeartbeatCheckArrayOutput) Index(i pulumi.IntInput) HeartbeatCheckOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *HeartbeatCheck {
		return vs[0].([]*HeartbeatCheck)[vs[1].(int)]
	}).(HeartbeatCheckOutput)
}

type HeartbeatCheckMapOutput struct{ *pulumi.OutputState }

func (HeartbeatCheckMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HeartbeatCheck)(nil)).Elem()
}

func (o HeartbeatCheckMapOutput) ToHeartbeatCheckMapOutput() HeartbeatCheckMapOutput {
	return o
}

func (o HeartbeatCheckMapOutput) ToHeartbeatCheckMapOutputWithContext(ctx context.Context) HeartbeatCheckMapOutput {
	return o
}

func (o HeartbeatCheckMapOutput) MapIndex(k pulumi.StringInput) HeartbeatCheckOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *HeartbeatCheck {
		return vs[0].(map[string]*HeartbeatCheck)[vs[1].(string)]
	}).(HeartbeatCheckOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HeartbeatCheckInput)(nil)).Elem(), &HeartbeatCheck{})
	pulumi.RegisterInputType(reflect.TypeOf((*HeartbeatCheckArrayInput)(nil)).Elem(), HeartbeatCheckArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HeartbeatCheckMapInput)(nil)).Elem(), HeartbeatCheckMap{})
	pulumi.RegisterOutputType(HeartbeatCheckOutput{})
	pulumi.RegisterOutputType(HeartbeatCheckArrayOutput{})
	pulumi.RegisterOutputType(HeartbeatCheckMapOutput{})
}
