// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Outputs
{

    [OutputType]
    public sealed class GetPagespeedMonitoringLocationsLocationResult
    {
        /// <summary>
        /// Location description
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Location IPv4 address
        /// </summary>
        public readonly string Ipv4;
        /// <summary>
        /// Location IPv6 address
        /// </summary>
        public readonly string Ipv6;
        /// <summary>
        /// Location region
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Location region code
        /// </summary>
        public readonly string RegionCode;
        /// <summary>
        /// Location status
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetPagespeedMonitoringLocationsLocationResult(
            string description,

            string ipv4,

            string ipv6,

            string region,

            string regionCode,

            string status)
        {
            Description = description;
            Ipv4 = ipv4;
            Ipv6 = ipv6;
            Region = region;
            RegionCode = regionCode;
            Status = status;
        }
    }
}
