// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Outputs
{

    [OutputType]
    public sealed class SslCheckMonitoredResource
    {
        /// <summary>
        /// URL of the server under test
        /// </summary>
        public readonly string Address;
        /// <summary>
        /// Hostname of the server under test
        /// </summary>
        public readonly string? Hostname;

        [OutputConstructor]
        private SslCheckMonitoredResource(
            string address,

            string? hostname)
        {
            Address = address;
            Hostname = hostname;
        }
    }
}
