// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Outputs
{

    [OutputType]
    public sealed class UptimeCheckTcpCheck
    {
        /// <summary>
        /// Authentication configuration block
        /// </summary>
        public readonly Outputs.UptimeCheckTcpCheckAuthentication? Authentication;
        /// <summary>
        /// Destination port for TCP checks
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Type of TCP check. Either SMTP, SSH or TCP
        /// </summary>
        public readonly string? Protocol;
        /// <summary>
        /// The number of seconds to wait to receive the first byte
        /// </summary>
        public readonly int? Timeout;

        [OutputConstructor]
        private UptimeCheckTcpCheck(
            Outputs.UptimeCheckTcpCheckAuthentication? authentication,

            int port,

            string? protocol,

            int? timeout)
        {
            Authentication = authentication;
            Port = port;
            Protocol = protocol;
            Timeout = timeout;
        }
    }
}
