// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Outputs
{

    [OutputType]
    public sealed class UptimeCheckIcmpCheck
    {
        /// <summary>
        /// Dummy attribute to allow for a nested block. This field should not be changed
        /// </summary>
        public readonly bool? Enabled;

        [OutputConstructor]
        private UptimeCheckIcmpCheck(bool? enabled)
        {
            Enabled = enabled;
        }
    }
}
