// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Outputs
{

    [OutputType]
    public sealed class UptimeCheckHttpCheckContentMatchers
    {
        /// <summary>
        /// String to look for within the response. Considered down if not found
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// Include header content in string match search
        /// </summary>
        public readonly bool? IncludeHeaders;
        /// <summary>
        /// Whether to consider the check as down if the content is present within the response
        /// </summary>
        public readonly string? Matcher;

        [OutputConstructor]
        private UptimeCheckHttpCheckContentMatchers(
            string content,

            bool? includeHeaders,

            string? matcher)
        {
            Content = content;
            IncludeHeaders = includeHeaders;
            Matcher = matcher;
        }
    }
}
