# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetPagespeedMonitoringLocationsResult',
    'AwaitableGetPagespeedMonitoringLocationsResult',
    'get_pagespeed_monitoring_locations',
    'get_pagespeed_monitoring_locations_output',
]

@pulumi.output_type
class GetPagespeedMonitoringLocationsResult:
    """
    A collection of values returned by getPagespeedMonitoringLocations.
    """
    def __init__(__self__, id=None, locations=None, region_code=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if locations and not isinstance(locations, list):
            raise TypeError("Expected argument 'locations' to be a list")
        pulumi.set(__self__, "locations", locations)
        if region_code and not isinstance(region_code, str):
            raise TypeError("Expected argument 'region_code' to be a str")
        pulumi.set(__self__, "region_code", region_code)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def locations(self) -> Sequence['outputs.GetPagespeedMonitoringLocationsLocationResult']:
        return pulumi.get(self, "locations")

    @property
    @pulumi.getter(name="regionCode")
    def region_code(self) -> Optional[str]:
        return pulumi.get(self, "region_code")


class AwaitableGetPagespeedMonitoringLocationsResult(GetPagespeedMonitoringLocationsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPagespeedMonitoringLocationsResult(
            id=self.id,
            locations=self.locations,
            region_code=self.region_code)


def get_pagespeed_monitoring_locations(region_code: Optional[str] = None,
                                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPagespeedMonitoringLocationsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['regionCode'] = region_code
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations', __args__, opts=opts, typ=GetPagespeedMonitoringLocationsResult).value

    return AwaitableGetPagespeedMonitoringLocationsResult(
        id=pulumi.get(__ret__, 'id'),
        locations=pulumi.get(__ret__, 'locations'),
        region_code=pulumi.get(__ret__, 'region_code'))
def get_pagespeed_monitoring_locations_output(region_code: Optional[pulumi.Input[Optional[str]]] = None,
                                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPagespeedMonitoringLocationsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['regionCode'] = region_code
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations', __args__, opts=opts, typ=GetPagespeedMonitoringLocationsResult)
    return __ret__.apply(lambda __response__: GetPagespeedMonitoringLocationsResult(
        id=pulumi.get(__response__, 'id'),
        locations=pulumi.get(__response__, 'locations'),
        region_code=pulumi.get(__response__, 'region_code')))
