// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Inputs
{

    public sealed class HeartbeatCheckMonitoredResourceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the hosting provider
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        public HeartbeatCheckMonitoredResourceGetArgs()
        {
        }
        public static new HeartbeatCheckMonitoredResourceGetArgs Empty => new HeartbeatCheckMonitoredResourceGetArgs();
    }
}
