// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Inputs
{

    public sealed class PagespeedCheckMonitoredResourceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL or IP address of the website under test
        /// </summary>
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        public PagespeedCheckMonitoredResourceGetArgs()
        {
        }
        public static new PagespeedCheckMonitoredResourceGetArgs Empty => new PagespeedCheckMonitoredResourceGetArgs();
    }
}
