// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Inputs
{

    public sealed class SslCheckMonitoredResourceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL of the server under test
        /// </summary>
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        /// <summary>
        /// Hostname of the server under test
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        public SslCheckMonitoredResourceGetArgs()
        {
        }
        public static new SslCheckMonitoredResourceGetArgs Empty => new SslCheckMonitoredResourceGetArgs();
    }
}
