// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Inputs
{

    public sealed class UptimeCheckMonitoredResourceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL, FQDN, or IP address of the server under test
        /// </summary>
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        /// <summary>
        /// Name of the hosting provider
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        public UptimeCheckMonitoredResourceGetArgs()
        {
        }
        public static new UptimeCheckMonitoredResourceGetArgs Empty => new UptimeCheckMonitoredResourceGetArgs();
    }
}
