// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Inputs
{

    public sealed class UptimeCheckHttpCheckContentMatchersArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// String to look for within the response. Considered down if not found
        /// </summary>
        [Input("content", required: true)]
        public Input<string> Content { get; set; } = null!;

        /// <summary>
        /// Include header content in string match search
        /// </summary>
        [Input("includeHeaders")]
        public Input<bool>? IncludeHeaders { get; set; }

        /// <summary>
        /// Whether to consider the check as down if the content is present within the response
        /// </summary>
        [Input("matcher")]
        public Input<string>? Matcher { get; set; }

        public UptimeCheckHttpCheckContentMatchersArgs()
        {
        }
        public static new UptimeCheckHttpCheckContentMatchersArgs Empty => new UptimeCheckHttpCheckContentMatchersArgs();
    }
}
