// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPagespeedMonitoringLocations(args?: GetPagespeedMonitoringLocationsArgs, opts?: pulumi.InvokeOptions): Promise<GetPagespeedMonitoringLocationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations", {
        "regionCode": args.regionCode,
    }, opts);
}

/**
 * A collection of arguments for invoking getPagespeedMonitoringLocations.
 */
export interface GetPagespeedMonitoringLocationsArgs {
    regionCode?: string;
}

/**
 * A collection of values returned by getPagespeedMonitoringLocations.
 */
export interface GetPagespeedMonitoringLocationsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly locations: outputs.GetPagespeedMonitoringLocationsLocation[];
    readonly regionCode?: string;
}
export function getPagespeedMonitoringLocationsOutput(args?: GetPagespeedMonitoringLocationsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPagespeedMonitoringLocationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations", {
        "regionCode": args.regionCode,
    }, opts);
}

/**
 * A collection of arguments for invoking getPagespeedMonitoringLocations.
 */
export interface GetPagespeedMonitoringLocationsOutputArgs {
    regionCode?: pulumi.Input<string>;
}
