// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getUptimeMonitoringLocations(args?: GetUptimeMonitoringLocationsArgs, opts?: pulumi.InvokeOptions): Promise<GetUptimeMonitoringLocationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("statuscake:index/getUptimeMonitoringLocations:getUptimeMonitoringLocations", {
        "regionCode": args.regionCode,
    }, opts);
}

/**
 * A collection of arguments for invoking getUptimeMonitoringLocations.
 */
export interface GetUptimeMonitoringLocationsArgs {
    regionCode?: string;
}

/**
 * A collection of values returned by getUptimeMonitoringLocations.
 */
export interface GetUptimeMonitoringLocationsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly locations: outputs.GetUptimeMonitoringLocationsLocation[];
    readonly regionCode?: string;
}
export function getUptimeMonitoringLocationsOutput(args?: GetUptimeMonitoringLocationsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUptimeMonitoringLocationsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("statuscake:index/getUptimeMonitoringLocations:getUptimeMonitoringLocations", {
        "regionCode": args.regionCode,
    }, opts);
}

/**
 * A collection of arguments for invoking getUptimeMonitoringLocations.
 */
export interface GetUptimeMonitoringLocationsOutputArgs {
    regionCode?: pulumi.Input<string>;
}
